const DUMMY_POSTS = [
  {
    id: '1',
    category: '일반',
    title: '같이 샤넬 챌린지 하실 분 구해요',
    content:
      '홍대입구역에서 15~18시쯤 모여서 촬영하실 분 구합니다! 제 채널 보시고 잘 어울릴 것 같은 분은 댓글 주세요!',
    author: {
      name: '혜안',
      handle: '@hxxax',
      profileImage: 'https://picsum.photos/200',
      isCreator: true,
      platform: 'youtube',
    },
    timeAgo: '1시간 전',
    likeCount: 34,
    commentCount: 6,
    imageUrls: [],
    comments: [
      {
        id: 'c1',
        author: {
          name: '크리에이터',
          handle: '@creator',
          profileImage: 'https://picsum.photos/201',
          isCreator: true,
          platform: 'youtube',
        },
        text: '저 하고 싶어요! 시간대도 딱 맞네요.',
        timeAgo: '1시간 전',
        replies: [
          {
            id: 'r1',
            author: {
              name: '혜안',
              handle: '@hxxax',
              profileImage: 'https://picsum.photos/200',
              isCreator: true,
              platform: 'youtube',
            },
            text: '제 채널로 DM 주세요!',
            timeAgo: '50분 전',
          },
          {
            id: 'r2',
            author: {
              name: '크리에이터',
              handle: '@creator',
              profileImage: 'https://picsum.photos/201',
              isCreator: true,
              platform: 'youtube',
            },
            text: '네! 지금 바로 보낼게요.',
            timeAgo: '45분 전',
          },
          {
            id: 'r3',
            author: {
              name: '혜안',
              handle: '@hxxax',
              profileImage: 'https://picsum.photos/200',
              isCreator: true,
              platform: 'youtube',
            },
            text: '확인했습니다! 상세 내용은 거기서 논의해요.',
            timeAgo: '30분 전',
          },
        ],
      },
      {
        id: 'c2',
        author: {
          name: '모델지망생',
          handle: '@model_hope',
          profileImage: 'https://picsum.photos/210',
          isCreator: false,
          platform: 'instagram',
        },
        text: '혹시 초보자도 참여 가능할까요? 채널 색감이 너무 예뻐서 꼭 참여하고 싶어요.',
        timeAgo: '40분 전',
        replies: [],
      },
      {
        id: 'c3',
        author: {
          name: '촬영러',
          handle: '@video_maker',
          profileImage: 'https://picsum.photos/211',
          isCreator: true,
          platform: 'tiktok',
        },
        text: '홍대면 가깝네요! 혹시 장비 지원도 필요한가요?',
        timeAgo: '20분 전',
        replies: [],
      },
    ],
  },
  {
    id: '2',
    category: '팁',
    title: '장소 꿀팁: 00입구역 근처 촬영 스팟 3곳',
    content:
      '자연광이 예쁘게 들어오는 00입구역 근처 촬영 스팟 3곳을 공유합니다. 가성비 좋은 공간 위주로 모았으니 확인해 보세요!',
    author: {
      name: '스팟마스터',
      handle: '@spot_m',
      profileImage: 'https://picsum.photos/203',
      isCreator: true,
      platform: 'instagram',
    },
    timeAgo: '1시간 전',
    likeCount: 120,
    commentCount: 15,
    imageUrls: [
      'https://picsum.photos/400/300',
      'https://picsum.photos/400/301',
      'https://picsum.photos/400/302',
    ],
    comments: [
      {
        id: 'c4',
        author: {
          name: '나그네',
          handle: '@traveler',
          profileImage: 'https://picsum.photos/212',
          isCreator: false,
          platform: 'instagram',
        },
        text: '와, 여기 진짜 가보고 싶던 곳인데 정보 감사합니다!',
        timeAgo: '45분 전',
        replies: [],
      },
      {
        id: 'c5',
        author: {
          name: '사진작가A',
          handle: '@photo_a',
          profileImage: 'https://picsum.photos/213',
          isCreator: true,
          platform: 'youtube',
        },
        text: '두 번째 스팟은 오전 10시쯤 빛이 제일 예쁘더라고요.',
        timeAgo: '30분 전',
        replies: [],
      },
      {
        id: 'c6',
        author: {
          name: '취미인',
          handle: '@hobby_ist',
          profileImage: 'https://picsum.photos/214',
          isCreator: false,
          platform: 'tiktok',
        },
        text: '대여료가 얼마 정도인지 혹시 알 수 있을까요?',
        timeAgo: '10분 전',
        replies: [],
      },
    ],
  },
  {
    id: '3',
    category: '같이 촬영해요',
    title: '급! 야외 촬영 모델 구합니다 (내일)',
    content:
      '00시 공원에서 진행하는 000 컨셉의 야외 촬영 모델 구인합니다. 포트폴리오 목적으로 진행되며, 페이는 소정 지급합니다.',
    author: {
      name: '포토그래퍼',
      handle: '@photo_graph',
      profileImage: 'https://picsum.photos/204',
      isCreator: false,
      platform: 'tiktok',
    },
    timeAgo: '2시간 전',
    likeCount: 90,
    commentCount: 8,
    imageUrls: ['https://picsum.photos/400/303'],
    comments: [
      {
        id: 'c7',
        author: {
          name: '지원자1',
          handle: '@apply_1',
          profileImage: 'https://picsum.photos/215',
          isCreator: false,
          platform: 'instagram',
        },
        text: '내일 오후 시간 가능합니다! 포트폴리오 어디로 보내면 될까요?',
        timeAgo: '1시간 전',
        replies: [],
      },
      {
        id: 'c8',
        author: {
          name: '궁금이',
          handle: '@question',
          profileImage: 'https://picsum.photos/216',
          isCreator: false,
          platform: 'youtube',
        },
        text: '촬영 시간이 대략 몇 시간 정도 소요될까요?',
        timeAgo: '50분 전',
        replies: [],
      },
      {
        id: 'c9',
        author: {
          name: '프리랜서',
          handle: '@free_lancer',
          profileImage: 'https://picsum.photos/217',
          isCreator: true,
          platform: 'tiktok',
        },
        text: '페이 협의 가능한가요?',
        timeAgo: '30분 전',
        replies: [],
      },
    ],
  },
  {
    id: '4',
    category: '일반',
    title: '강남 스튜디오 대여합니다 (오후)',
    content:
      '강남역 근처 인테리어 깔끔한 스튜디오 오후 시간대 저렴하게 대여해 드립니다.',
    author: {
      name: '스튜디오대여',
      handle: '@studio_rent',
      profileImage: 'https://picsum.photos/205',
      isCreator: false,
      platform: 'instagram',
    },
    timeAgo: '3시간 전',
    likeCount: 205,
    commentCount: 22,
    imageUrls: [
      'https://picsum.photos/400/304',
      'https://picsum.photos/400/305',
      'https://picsum.photos/400/306',
      'https://picsum.photos/400/307',
      'https://picsum.photos/400/308',
    ],
    comments: [
      {
        id: 'c10',
        author: {
          name: '대여희망',
          handle: '@rent_hope',
          profileImage: 'https://picsum.photos/218',
          isCreator: false,
          platform: 'instagram',
        },
        text: '이번 주 금요일 오후 2시 예약 가능한가요?',
        timeAgo: '2시간 전',
        replies: [],
      },
      {
        id: 'c11',
        author: {
          name: '공간러버',
          handle: '@space_lover',
          profileImage: 'https://picsum.photos/219',
          isCreator: false,
          platform: 'youtube',
        },
        text: '여기 주차 가능한가요?',
        timeAgo: '1시간 전',
        replies: [],
      },
      {
        id: 'c12',
        author: {
          name: 'PD님',
          handle: '@pd_nim',
          profileImage: 'https://picsum.photos/220',
          isCreator: true,
          platform: 'tiktok',
        },
        text: '조명 장비도 구비되어 있는지 궁금합니다.',
        timeAgo: '30분 전',
        replies: [],
      },
    ],
  },
  {
    id: '5',
    category: '팁',
    title: '편집 시간 단축 팁: 프리미어 프로 단축키 5가지',
    content:
      '영상 편집 시간을 획기적으로 줄여줄 프리미어 프로의 숨겨진 단축키 5가지를 공개합니다.',
    author: {
      name: '편집왕',
      handle: '@edit_king',
      profileImage: 'https://picsum.photos/206',
      isCreator: true,
      platform: 'youtube',
    },
    timeAgo: '1일 전',
    likeCount: 301,
    commentCount: 55,
    imageUrls: [
      'https://picsum.photos/400/309',
      'https://picsum.photos/400/310',
    ],
    comments: [
      {
        id: 'c13',
        author: {
          name: '입문자',
          handle: '@beginner',
          profileImage: 'https://picsum.photos/221',
          isCreator: false,
          platform: 'youtube',
        },
        text: 'Q랑 W만 알아도 삶의 질이 달라지죠!',
        timeAgo: '20시간 전',
        replies: [],
      },
      {
        id: 'c14',
        author: {
          name: '실무자',
          handle: '@pro_editor',
          profileImage: 'https://picsum.photos/222',
          isCreator: true,
          platform: 'instagram',
        },
        text: '추가로 중첩(Nest) 단축키도 지정해두면 편합니다.',
        timeAgo: '15시간 전',
        replies: [],
      },
      {
        id: 'c15',
        author: {
          name: '학생',
          handle: '@student',
          profileImage: 'https://picsum.photos/223',
          isCreator: false,
          platform: 'tiktok',
        },
        text: '정리해주셔서 감사합니다! 바로 써먹어볼게요.',
        timeAgo: '10시간 전',
        replies: [],
      },
    ],
  },
  {
    id: '6',
    category: '같이 촬영해요',
    title: '주말 홍대입구역 댄스 영상 촬영 크루 모집',
    content:
      '주말에 홍대입구역 근처에서 댄스 커버 영상을 촬영할 크루를 모집합니다.',
    author: {
      name: '댄스홀릭',
      handle: '@dance_holic',
      profileImage: 'https://picsum.photos/207',
      isCreator: false,
      platform: 'tiktok',
    },
    timeAgo: '2일 전',
    likeCount: 88,
    commentCount: 11,
    imageUrls: [
      'https://picsum.photos/400/311',
      'https://picsum.photos/400/312',
      'https://picsum.photos/400/313',
      'https://picsum.photos/400/314',
    ],
    comments: [],
  },
];

export default DUMMY_POSTS;
